### ISSUE TITLE
ServiceAccount not created in openshift

### ISSUE THREAD

**Issue by kenankule** [neuvector/neuvector-helm#144]
Hi,

May I ask what is the reason NOT creating the service account if openshift is selected as a target environment ? 
https://github.com/neuvector/neuvector-helm/blob/master/charts/core/templates/serviceaccount.yaml#L1

I'd expect the service account to be created if its different then default.

**Comment by andsont** [comment]
service account is required for the Privileged SCC before deployment neuvector. that is why we don't need to create it again in helm chart. please refer to our readme for details.

**Comment by kenankule** [comment]
You mean, only in openshift service account needs to be privileged? 
Even in that case, helm charts usually create the service account, and add the ClusterRoleBinding that allows using system:openshift:scc:privileged clusterrole.

>please refer to our readme for details.
Thats exactly my point. With this form, you need to maintain a set of "instructions" on how to create the service account separately in your readme. I'm failing to understand why it's not the charts responsibility and user only needs to set smth like 
```
serviceAccount:
  create: true
  privileged: true
```
during the installation of the charts. Thats what most helm charts do.

**Comment by andsont** [comment]
for oc 3.x, it is hard for us to use yaml file to grand our service account access to the privileged scc because the account information was stored in privileged scc. that is why we have this legacy approach for openshift 3.x.
```
$ oc -n neuvector adm policy add-scc-to-user privileged -z default
```

yes, u r right. for openshift 4.x. it is a different story and we should be able to have this approach u mentioned in our helm chart.
appreciate your suggestion. i have filed a jira case internally.

**Comment by kenankule** [comment]
I understand, ocp3 uses a different syntax/way to manage scc grants. Thanks!
