### ISSUE TITLE
Support for creating CRD resources outside of chart

### ISSUE THREAD

**Issue by ksandermann** [neuvector/neuvector-helm#64]
It would be nice if it would be configurable to NOT deploy the CRD resources inside of the helmchart.
This would make it possible to remove/purge the helm release without losing all resources of the CRD type (i.e. neuvectorrules)

**Comment by becitsthere** [comment]
Thanks for the suggestion. Here is what we plan to do,

We can add a new chart for crd, because crd can be deployed independently. For backward compatibility, we will leave crd template in the core and add an enable/disable variable. What you can do is to 'disable' the CRD template in the core chart, but use the newly created crd chart.

Do you think this works for you?

**Comment by ksandermann** [comment]
Hi @becitsthere,

absolutely, this is exactly what I had in mind :) 👍

**Comment by becitsthere** [comment]
PR 68: Separate CRD from the core chart.
